name: Playwright Tests # Nombre
on: #acciones que activan el proceso 
  push:
    branches: [ main, master ] #cuando se haga un push a las ramas
  pull_request:
    branches: [ main, master ] #cuando se haga un PR a las ramas
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest # SO donde se ejecuta
    steps:
    - uses: actions/checkout@v4 # hacer checkout del codigo
    - uses: actions/setup-node@v4 #instalar node en el contenedor
      with:
        node-version: lts/*
    - name: Install dependencies #instala dependencias
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30